config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :animedcs
  #get 'home/index'
  root 'animedcs#index'
  get 'home/about'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/animedc.rb
class Animedc < ApplicationRecord
	belongs_to :user
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

        has_many :animedc

end

app/controllers/animedcs_controller.rb
class AnimedcsController < ApplicationController
  before_action :set_animedc, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]
  
  # GET /animedcs or /animedcs.json
  def index
    @animedcs = Animedc.all
  end

  # GET /animedcs/1 or /animedcs/1.json
  def show
  end

  # GET /animedcs/new
  def new
    #@animedc = Animedc.new
    @animedc = current_user.animedc.build
  end

  # GET /animedcs/1/edit
  def edit
  end

  # POST /animedcs or /animedcs.json
  def create
    #@animedc = Animedc.new(animedc_params)
    @animedc = current_user.animedc.build(animedc_params)

    respond_to do |format|
      if @animedc.save
        format.html { redirect_to animedc_url(@animedc), notice: "Anime was successfully created." }
        format.json { render :show, status: :created, location: @animedc }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @animedc.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /animedcs/1 or /animedcs/1.json
  def update
    respond_to do |format|
      if @animedc.update(animedc_params)
        format.html { redirect_to animedc_url(@animedc), notice: "Anime was successfully updated." }
        format.json { render :show, status: :ok, location: @animedc }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @animedc.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /animedcs/1 or /animedcs/1.json
  def destroy
    @animedc.destroy!

    respond_to do |format|
      format.html { redirect_to animedcs_url, notice: "Anime was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def correct_user
    @animedc = current_user.animedc.find_by(id: params[:id])
    redirect_to animedc_path, notice: "Not Authroized to Edit" if @animedc.nil?
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_animedc
      @animedc = Animedc.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def animedc_params
      params.require(:animedc).permit(:anime_name, :authour, :watched, :rating, :user_id)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  def about
    @about_me = "My name is Gui Zamorano"
  end
end

app/helpers/animedcs_helper.rb
module AnimedcsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/animedcs/_animedc.html.erb
<div id="<%= dom_id animedc %>">
  <p>
    <strong>Anime name:</strong>
    <%= animedc.anime_name %>
  </p>

  <p>
    <strong>Authour:</strong>
    <%= animedc.authour %>
  </p>

  <p>
    <strong>Watched:</strong>
    <%= animedc.watched %>
  </p>

  <p>
    <strong>Rating:</strong>
    <%= animedc.rating %>
  </p>

</div>

app/views/animedcs/_form.html.erb
<%= form_with(model: animedc) do |form| %>
  <% if animedc.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(animedc.errors.count, "error") %> prohibited this animedc from being saved:</h2>

      <ul>
        <% animedc.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.text_field :anime_name, class:"form-control", placeholder:"Anime Name" %>
  </div>

  <div class="field form-group">
    <%= form.text_field :authour, class:"form-control", placeholder:"Author Name" %>
  </div>

  <div class="field form-group">
    <%= form.label :watched, style: "display: block" %>
    <%= form.check_box :watched, class:"form-control" %>
  </div>

  <div class="field form-group">
    <%= form.label :rating, style: "display: block" %>
    <%= form.number_field :rating, class:"form-control" %>
  </div>
  <div class="field form-group">
    <% form.label :user_id, style: "display: block" %>
    <%= form.number_field :user_id, id: :animedc_user_id, class:"form-control", value: current_user.id, type: :hidden %>
  </div>

  <div class="actions">

    <% if @animedc.id.present? %>
  <%= form.submit "Update Anime" , class:"btn btn-secondary"%>
<% else %>
  <%= form.submit "Add Anime" , class:"btn btn-secondary"%>
<% end %>
  </div>
<% end %>

app/views/animedcs/edit.html.erb
<h1>Editing Anime</h1>

<%= render "form", animedc: @animedc %>

<br>

<div>
  <%= link_to "Back to Anime List", animedcs_path, class:"btn btn-secondary" %>
</div>

app/views/animedcs/index.html.erb
<h1>Anime List</h1>
<% if user_signed_in? %>
<table class="table table-stirped table-bordered table-hover">
  <thead class="thead-dark">
    <tr>
      <th>Anime</th>
      <th>Author</th>
      <th>Watched?</th>
      <th>Rating</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
  <% @animedcs.each do |animedc| %>
  <% if animedc.user == current_user %>
  <tr>
    <td><%= link_to animedc.anime_name, animedc %></td>
    <td><%= animedc.authour %></td>
    <td><%= animedc.watched %></td>
    <td><%= animedc.rating %></td>
    <td><%= link_to 'Show', animedc %></td>
    <td><%= link_to 'Edit', edit_animedc_path(animedc) %></td>
  </tr>
  <% end%>
  <% end %>
   </tbody>
</table>

<br>
 


<%= link_to "Add New Anime", new_animedc_path, class:"btn btn-secondary"%>

<% else %>

<h1>Home Page</h1>
<p>Login to See List</p>

<% end %>

app/views/animedcs/new.html.erb
<h1>New Anime</h1>

<%= render "form", animedc: @animedc %>

<br>

<div>
  <%= link_to "Back to Anime List", animedcs_path, class:"btn btn-secondary" %>
</div>

app/views/animedcs/show.html.erb
<div class="jumbotron">
  <h1 class="display-4"><%= @animedc.anime_name %></h1>
  <p class="lead"><%= @animedc.authour %></p>
  <hr class="my-4">
  <p>Watched? <%= @animedc.watched %> |  Rating: <%= @animedc.rating %></p>
   <%= link_to "Edit this Entry", edit_animedc_path(@animedc), class:"btn btn-secondary" %> 
  <%= link_to "Back to Anime List", animedcs_path, class:"btn btn-secondary" %>

  <%= button_to "Delete this Entry", @animedc, method: :delete, class:"btn btn-danger" %>
</div>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <%= link_to 'Anime App', root_path, class:"navbar-brand"%>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to "About Us", home_about_path, class:"nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Anime List", animedcs_path, class:"nav-link" %>
      </li>
      <% if user_signed_in? %>
      
      <li class="nav-item">
        <%= link_to "Edit Profile", edit_user_registration_path, class:"nav-link" %>
      </li>
      <li class="nav-item">
        <%= button_to "Sign Out", destroy_user_session_path, method: :delete, class:"btn bg-transparent btn-outline-primary" %>
      </li>
      <% else %>
      <li class="nav-item">
        <%= link_to "Sign Up", new_user_registration_path, class:"nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Sign In", new_user_session_path, class:"nav-link" %>
      </li>
      <% end %>
      
      
      
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

app/views/home/about.html.erb
<h1>About Us</h1>
<p>
	<%= @about_me %>
</p>

app/views/home/index.html.erb
<h1>Home Page</h1>
<p>Login to See List</p>

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <title>Anime App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <%= render 'home/header' %>
    <div class="container">
      <br>
      <% if notice %>
        <%= render 'layouts/alerts' %>
      <% end %>
      <br/>
    <%= yield %>
  </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>